name: Fail demo

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/requirements-latest.yml
      - run: mamba list
