name: Documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: 3.7
          environment-file: ci/requirements-docs.yml
          activate-environment: TEMPLATE-docs
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Install
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd doc
          make html

      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: doc/_build/html
