name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-file: ci/requirements-docs.yml
          cache-environment: true

      - name: Show conda options
        run: conda config --show

      - name: conda info
        run: conda info

      - name: conda list
        run: conda list

      - name: Install
        run: python -m pip install --no-deps -e .

      - name: Build docs
        run: sphinx-build -n -j auto -b html -d build/doctrees doc build/html

      - uses: actions/upload-artifact@v4
        with:
          name: TEMPLATE-docs
          path: build/html
