name: Test latest

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

jobs:
  build:
    name: ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ci/requirements.yml
          activate-environment: TEMPLATE
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Install
        shell: bash -l {0}
        run: python -m pip install --no-deps -e .

      - name: pytest
        shell: bash -l {0}
        run: coverage run -m pytest -v

      - name: codecov.io
        uses: codecov/codecov-action@v1
        with:
          # TODO:
          # 1. acquire token from codecov.io
          # 2. add token to https://github.com/<login>/<project>/settings/secrets/
          token: ${{ secrets.CODECOV_TOKEN }}
