name: Test latest

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']


jobs:
  build:
    name: ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ci/requirements.yml
          activate-environment: TEMPLATE
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Install
        run: |
          python -m pip install --no-deps -e .

      - name: pytest
        run: py.test --verbose TEMPLATE --cov=TEMPLATE --cov-config ci/.coveragerc
             --cov-report term-missing

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
