name: Test latest

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.requirements }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.8']
        requirements: [latest, minimal]
        include:
          - os: ubuntu
            python-version: '3.9'
            requirements: latest
          - os: ubuntu
            python-version: '3.10'
            requirements: latest
          - os: ubuntu
            python-version: '3.11'
            requirements: latest
          - os: ubuntu
            python-version: '3.12'
            requirements: latest
          - os: macos
            python-version: '3.12'
            requirements: latest
          - os: windows
            python-version: '3.12'
            requirements: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          condarc-file: ci/condarc
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          environment-file: ci/requirements-${{ matrix.requirements }}.yml
          activate-environment: TEMPLATE

      - name: Show conda options
        run: conda config --show

      - name: conda info
        run: conda info

      - name: conda list
        run: conda list

      - name: Install
        run: python -m pip install --no-deps -e .

      - name: pytest
        run: coverage run -m pytest -v

      - name: Generate Coverage XML report
        run: coverage xml

      - name: codecov.io
        uses: codecov/codecov-action@v1
