name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.requirements }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        requirements: [latest]
        include:
          # Test on macos and windows (first and last version of python only)
          - os: macos
            python-version: '3.8'
            requirements: latest
          - os: macos
            python-version: '3.12'
            requirements: latest
          - os: windows
            python-version: '3.8'
            requirements: latest
          - os: windows
            python-version: '3.12'
            requirements: latest
          # Test on minimal requirements
          - os: ubuntu
            python-version: '3.8'
            requirements: minimal
          - os: macos
            python-version: '3.8'
            requirements: minimal
          - os: windows
            python-version: '3.8'
            requirements: minimal

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          condarc-file: ci/condarc
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          environment-file: ci/requirements-${{ matrix.requirements }}.yml
          activate-environment: TEMPLATE

      - name: Show conda options
        shell: bash -l {0}
        run: conda config --show

      - name: conda info
        shell: bash -l {0}
        run: conda info

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: Install
        shell: bash -l {0}
        run: python -m pip install --no-deps -e .

      - name: pytest
        shell: bash -l {0}
        run: |
          coverage run -m pytest -v
          coverage xml

      - name: codecov.io
        uses: codecov/codecov-action@v1
